Slasher + Powerful Swipe HoA
BigWigsMods/LittleWigs pull request #576
Opened 2021-02-04 22:39 UTC by okazan

Hey dont know how to use github nor do i know lua but I frankensteined what I could with what I do know.

lmk how i did or if im wasting my time, just attempted this for fun.

tyty

2021-02-04 23:10 UTC, Zireael-N requested changes

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Locales/esES.lua
> +	L.slasher = "Stoneborn Slasher"
Revert this change.

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Options/Colors.lua
> +	[326997] = "yellow",
These files are auto-generated, revert this change.

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Options/Sounds.lua
> +	[326997] = "alert",
These files are auto-generated, revert this change.

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Trash.lua
> +	167607 -- Stonebron Slasher
There's a typo in the mob's name.

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Trash.lua
> +-- Stoneborn Slaher
Typo.

2021-02-04 23:10 UTC, Zireael-N commented on Shadowlands/HallsOfAtonement/Trash.lua
> +	self:Message(args.spellId, "yellow", CL.casting:format(args.spellName))
We use `purple` for tank abilities.

2021-02-05 00:12 UTC, okazan commented
Did i do it? IDK how to operate github like AT ALL so sorry if im burning ur time lol

much appreciated

2021-02-05 08:04 UTC, merged

2021-02-05 08:04 UTC, Zireael-N commented
Thanks!